#version: '3.8'
#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db-1:3307/charging_stations_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_FLYWAY_ENABLED: true
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: charging_stations_db
#      MYSQL_TCP_PORT: 3307
#    ports:
#      - "3307:3306"

version: "3.7"
services:
  api_service:
    build: .
    ports:
      - 8090:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/charging_stations_db
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.flyway.enabled=true
    restart: on-failure
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - 3308:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: charging_stations_db
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net:



#version: '3.8'
#services:
#  app:
#    build: .
#    ports:
#      - "8081:8080"
#    depends_on:
#      db:
#        condition: service_healthy  # Чекати, доки контейнер db буде готовий
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://$${MYSQL_HOST:localhost}:3307/charging_stations_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_JPA_HIBERNATE_DDL_AUTO: none
#      SPRING_FLYWAY_ENABLED: true
#    restart: on-failure
#
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: charging_stations_db
#    ports:
#      - "3307:3306"
#    healthcheck:  # Перевірка готовності контейнера
#      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
#      interval: 10s
#      retries: 5
#      timeout: 5s
#      start_period: 30s
#
